GenAITech/Controllers/GenAIsController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using GenAITech.Data;
using Microsoft.AspNetCore.Hosting;
using Microsoft.AspNetCore.Hosting;
using System.IO;

namespace GenAITech.Models
{
    public class GenAIsController : Controller
    {
        private readonly ApplicationDbContext _context;
        private readonly IWebHostEnvironment _webHostEnvironment;

    
        public GenAIsController(ApplicationDbContext context, IWebHostEnvironment webHostEnvironment)
        {
            _context = context;
            _webHostEnvironment = webHostEnvironment;
        }

        // GET: GenAIs
        public async Task<IActionResult> Index()
        {
              return _context.GenAI != null ? 
                          View(await _context.GenAI.OrderByDescending(x=>x.Like).ToListAsync()) :
                          Problem("Entity set 'ApplicationDbContext.GenAI'  is null.");
        }

        // GET: GenAIs/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null || _context.GenAI == null)
            {
                return NotFound();
            }

            var genAI = await _context.GenAI
                .FirstOrDefaultAsync(m => m.Id == id);
            if (genAI == null)
            {
                return NotFound();
            }

            return View(genAI);
        }

        // GET: GenAIs/Create
        public IActionResult Create()
        {
            return View();
        }

        // POST: GenAIs/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create(GenAI genAI)
        {
            if (ModelState.IsValid)
            {
                if (genAI.ImageFile != null)
                {
                    var uniqueFileName = GetUniqueFileName(genAI.ImageFile.FileName);
                    var uploads = Path.Combine(_webHostEnvironment.WebRootPath, "images");
                    var filePath = Path.Combine(uploads, uniqueFileName);
                    genAI.ImageFilename = uniqueFileName;
                    using (var fileStream = new FileStream(filePath, FileMode.Create))
                    {
                        await genAI.ImageFile.CopyToAsync(fileStream);
                    }
                }
                genAI.AnchorLink = "Home/GenAiSites#Bard_tumbinal";
                _context.Add(genAI);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            return View(genAI);
        }
        private string GetUniqueFileName(string fileName)
{
    fileName = Path.GetFileName(fileName);
    return Path.GetFileNameWithoutExtension(fileName)
           + "_"
           + Guid.NewGuid().ToString().Substring(0, 4)
           + Path.GetExtension(fileName);
}

        // GET: GenAIs/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null || _context.GenAI == null)
            {
                return NotFound();
            }

            var genAI = await _context.GenAI.FindAsync(id);
            if (genAI == null)
            {
                return NotFound();
            }
            return View(genAI);
        }

        // POST: GenAIs/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, GenAI genAI)
        {
            if (id != genAI.Id)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    if (genAI.ImageFile != null)
                    {
                        var uniqueFileName = GetUniqueFileName(genAI.ImageFile.FileName);
                        var uploads = Path.Combine(_webHostEnvironment.WebRootPath, "images");
                        var filePath = Path.Combine(uploads, uniqueFileName);
                        genAI.ImageFilename = uniqueFileName;
                        using (var fileStream = new FileStream(filePath, FileMode.Create))
                        {
                            await genAI.ImageFile.CopyToAsync(fileStream);
                        }
                    }
                    genAI.AnchorLink = "Home/GenAiSites#Bard_tumbinal";
                    _context.Update(genAI);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!GenAIExists(genAI.Id))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            return View(genAI);
        }

        // GET: GenAIs/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null || _context.GenAI == null)
            {
                return NotFound();
            }

            var genAI = await _context.GenAI
                .FirstOrDefaultAsync(m => m.Id == id);
            if (genAI == null)
            {
                return NotFound();
            }

            return View(genAI);
        }

        // POST: GenAIs/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            if (_context.GenAI == null)
            {
                return Problem("Entity set 'ApplicationDbContext.GenAI'  is null.");
            }
            var genAI = await _context.GenAI.FindAsync(id);
            if (genAI != null)
            {
                _context.GenAI.Remove(genAI);
            }
            
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }


        [HttpPost]
        public async Task<IActionResult> IncrementLike(int id, int newLikeCount)
        {
            var genAI = await _context.GenAI.FindAsync(id);

            if (genAI == null)
            {
                return NotFound();
            }

            genAI.Like = newLikeCount;
            await _context.SaveChangesAsync();

            return Json(new { success = true });
        }

        private bool GenAIExists(int id)
        {
          return (_context.GenAI?.Any(e => e.Id == id)).GetValueOrDefault();
        }
    }
}

GenAITech/Controllers/HomeController.cs
using GenAITech.Data;
using GenAITech.Models;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using System.Diagnostics;

namespace GenAITech.Controllers
{
    public class HomeController : Controller
    {
        private readonly ApplicationDbContext _context;
        private readonly ILogger<HomeController> _logger;

            
        public HomeController(ILogger<HomeController> logger, ApplicationDbContext context)
        {
            _logger = logger;
            _context = context;
            
        }

        public async Task<IActionResult> IndexAsync()
        {
            return _context.GenAI != null ?
                         View(await _context.GenAI.ToListAsync()) :
                         Problem("Entity set 'ApplicationDbContext.GenAI'  is null.");
        }

        public IActionResult Privacy()
        {
            return View();
        }

        public IActionResult Contact()
        {
            return View();
        }

        public IActionResult GenAiTools()
        {
            return View();
        }

        public IActionResult GenAiOrganizasion()
        {
            return View();
        }

        public IActionResult GenAiApplications()
        {
            return View();
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

GenAITech/Controllers/JobsController.cs
using System.Formats.Asn1;
using System.Globalization;
using Microsoft.AspNetCore.Hosting;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using CsvHelper;
using System.Globalization;
using GenAITech.Models;
using CsvHelper.Configuration;
using System.IO;
using Newtonsoft.Json;

namespace GenAITech.Controllers
{
    public class JobsController : Controller

    {
        private readonly IWebHostEnvironment _webHostEnvironment;

        public JobsController(IWebHostEnvironment webHostEnvironment)
        {
            _webHostEnvironment = webHostEnvironment;
        }


        // GET: JobsController
        public ActionResult Index()
        {

            var jobDataList = new List<JobData>();

            using (var reader = new StreamReader(_webHostEnvironment.WebRootPath+ "/csv/salaries2023.csv"))
            using (var csv = new CsvReader(reader, System.Globalization.CultureInfo.InvariantCulture))
            {
                jobDataList = csv.GetRecords<JobData>().ToList();
            }
            

            var top10JobTitlesBySalary = jobDataList
                .GroupBy(j => j.job_title)
                 .Select(g => new
                         {
                          JobTitle = g.Key,
                    AverageSalary = g.Average(j => j.salary)
                })
                .OrderByDescending(x => x.AverageSalary)
                .Take(10)
                .ToDictionary(x => x.JobTitle, x => x.AverageSalary);
            ViewBag.TopJobTitlesBySalary = JsonConvert.SerializeObject(top10JobTitlesBySalary);

            var top5Companies = jobDataList
                .GroupBy(j => j.company_size)
                .OrderByDescending(g => g.Count())
                .Take(5)
                .SelectMany(g => g)
                .Take(5)
                .ToList();

            ViewBag.TopCompanies = top5Companies;

            var currentYear = DateTime.Now.Year;
            var salaryTotals = new Dictionary<int, decimal>();
            for (int year = currentYear - 3; year <= currentYear; year++)
            {
                decimal totalSalary = jobDataList.Where(j => j.work_year == year.ToString())
                                                 .Sum(j => j.salary);
                salaryTotals.Add(year, totalSalary);
            }
            ViewBag.SalaryTotals = salaryTotals;

            return View(top5Companies);


        }


    }
}
    

GenAITech/Views/Home/Contact.cshtml
@{
    ViewData["Title"] = "Contact";
}

<section class="contact">
    <img src="@Url.Content("/images/background/bg1.jpg")" alt="Picture">
    <div class="overlay-contact">
        <h2>Contact & About</h2>
        <div class="contact-box">
            <div class="box-1 box-set">
                <h3>
                    Contact Us
                </h3>
                <p>
                    This website was written by [your name]
                    To get in contact please email [link to your email address]
                </p>
            </div>
            <div class="box-2 box-set">
                <h3>About Us</h3>
                <p>
                    This website provides an introduction to Artificial Intelligence and was created as
                    partial fulfillment of the assessment requirements of Web Design and Programming at the
                    University of Canberra.
                    This site is built on the ASP.NET CORE framework and employs Bootstrap responsive design
                    techniques.
                </p>
            </div>
            <div class="box-3 box-set">
                <h3>
                    Copyright
                </h3>
                <p>
                    All images used in this website were downloaded from <a href="https://unsplash.com/">Unsplash</a>.
                </p>
                <p>
                    The icons for the footer from <a href="https://fontawesome.com/">fontawesome</a>.
                </p>
                <p>
                    The Anton font used for headers from <a href="https://fonts.google.com/"> Google Fonts</a>
                </p>
                <p>
                    The AI jobs dataset from <a href="https://ai-jobs.net/">Insights</a>
                    </p>
                <p>
                    The Python source from  <a href="https://www.kaggle.com/code/sowrabhghosh/data-science-salary-2020-22-analysis">Kaggle</a>
                    </p>
                <p>
                    The Python web based on PyScript from Real <a href="https://realpython.com/pyscript-python-in-browser">Python</a>
                    </p>
            </div>
        </div>
    </div>
</section>

GenAITech/Views/Home/GenAiApplications.cshtml
@{
    ViewData["Title"] = "GenAiTools";
}

<section class="contact">
    <img src="@Url.Content("/images/background/bg7.jpg")" alt="Picture">
    <div class="overlay-contact">
        <h2>GenAI Organizations</h2>
        <div class="container">
            <div class="row">
                <div class="col-lg-12">
                    <div class="featuredPropBox-3">
                        <ul>
                            <li>
                                <div>
                                    <div class="fptext">
                                        <p>ChatGPT</p>
                                        <div class="line"></div>
                                        <a asp-area="" asp-controller="Home" asp-action="GenAiTools">More Details</a>
                                        <div class="line"></div>
                                    </div>
                                </div>
                            </li>
                            <li>
                                <div>
                                    <div class="fptext">
                                        <p>GitHub Copilot</p>
                                        <div class="line"></div>
                                        <a asp-area="" asp-controller="Home" asp-action="GenAiTools">More Details</a>
                                        <div class="line"></div>
                                    </div>
                                </div>
                            </li>
                            <li>
                                <div>
                                    <div class="fptext">
                                        <p>DALL-E</p>
                                        <div class="line"></div>
                                        <a asp-area="" asp-controller="Home" asp-action="GenAiTools">More Details</a>
                                        <div class="line"></div>
                                    </div>
                                </div>
                            </li>
                            <li>
                                <div>
                                    <div class="fptext">
                                        <p>Synthesia</p>
                                        <div class="line"></div>
                                        <a asp-area="" asp-controller="Home" asp-action="GenAiTools">More Details</a>
                                        <div class="line"></div>
                                    </div>
                                </div>
                            </li>
                        </ul>
                    </div>
                </div>
            </div>
        </div>
    </div>
</section>

GenAITech/Views/Home/GenAiOrganizasion.cshtml
@{
    ViewData["Title"] = "GenAiTools";
}

<section class="contact">
    <img src="@Url.Content("/images/background/bg6.jpg")" alt="Picture">
    <div class="overlay-contact">
        <h2>GenAI Organizations</h2>
        <div class="container">
            <div class="row">
                <div class="col-lg-12">
                    <div class="featuredPropBox-2">
                        <ul>
                            <li>
                                <div>
                                    <div class="fptext">
                                        <p>Microsoft</p>
                                        <div class="line"></div>
                                        <a asp-area="" asp-controller="Home" asp-action="GenAiTools">More Details</a>
                                        <div class="line"></div>
                                    </div>
                                </div>
                            </li>
                            <li>
                                <div>
                                    <div class="fptext">
                                        <p>Google</p>
                                        <div class="line"></div>
                                        <a asp-area="" asp-controller="Home" asp-action="GenAiTools">More Details</a>
                                        <div class="line"></div>
                                    </div>
                                </div>
                            </li>
                            <li>
                                <div>
                                    <div class="fptext">
                                        <p>IBM</p>
                                        <div class="line"></div>
                                        <a asp-area="" asp-controller="Home" asp-action="GenAiTools">More Details</a>
                                        <div class="line"></div>
                                    </div>
                                </div>
                            </li>
                            <li>
                                <div>
                                    <div class="fptext">
                                        <p>Amazon</p>
                                        <div class="line"></div>
                                        <a asp-area="" asp-controller="Home" asp-action="GenAiTools">More Details</a>
                                        <div class="line"></div>
                                    </div>
                                </div>
                            </li>
                        </ul>
                    </div>
                </div>
            </div>
        </div>
    </div>
</section>

GenAITech/Views/Home/Index.cshtml
@using Microsoft.AspNetCore.Identity
@using GenAITech
@model IEnumerable<GenAITech.Models.GenAI>
@inject SignInManager<IdentityUser> SignInManager
@inject UserManager<IdentityUser> UserManager
@{
    ViewData["Title"] = "Home Page";
}

<style>
    
</style>



@if (SignInManager.IsSignedIn(User))
{
    <div class="hero-section">
        <video loop muted autoplay="autoplay" preload="auto" id="background-video">
            <source src="@Url.Content("~/videos/video.mp4")" type="video/mp4">
        </video>
        <div class="overlay"></div>
        <div class="video-content">
            <h1 class="main-heading">Generative AI Technology</h1>
            <div class="content">
                <p>
                    Any time an AI technology is generating something on its own, it can be referred to as
                    "generative AI." This umbrella term includes learning algorithms that make predictions
                    as well as those that can use prompts to autonomously write articles and paint pictures.
                    Techopedia
                </p>
            </div>
        </div>
    </div>
    <div class="parallax-container ">
        <div class="blog-card">
            <div class="description">
                <h1>
                    GenAI Tools
                </h1>
                <p>
                    Generative AI tools refer to software or systems that use neural network techniques to
                    process and comprehend input data, subsequently producing meaningful responses.
                    Scribehow
                </p>
                <div class="read-more">
                    <a asp-area="" asp-controller="Home" asp-action="GenAiTools">Read More</a>
                </div>
            </div>
            <div class="images">
                <div class="image-1">
                    <img src="@Url.Content("/images/genaisites/bard_thumbnail.jpg")"
                         alt="" />
                </div>
                <div class="image-2">
                    <img src="@Url.Content("/images/genaisites/midjourney_thumbnail.jpg")"
                         alt="" />
                </div>
            </div>
        </div>
            <div class="blog-card">
                <div class="images">
                    <div class="image-1">
                        <img src="@Url.Content("/images/genaisites/ms_thumbnail.jpg")"
                             alt="" />
                    </div>
                    <div class="image-2">
                        <img src="@Url.Content("/images/genaisites/google_thumbnail.jpg")"
                             alt="" />
                    </div>
                </div>
                <div class="description">
                    <h1>
                        GenAI Organisations
                    </h1>
                    <p>
                        Generative AI Organizations like Microsoft, Google, Amazon and IBM have invested
                        hundreds of millions of dollars and massive compute power to build the foundational
                        models on which services like ChatGPT and others depend.
                        Gartner
                    </p>
                    <div class="read-more">
                    <a asp-area="" asp-controller="Home" asp-action="GenAiOrganizasion">Read More</a>
                    </div>
                </div>

            </div>
        <div class="blog-card">
            <div class="description">
                <h1>
                    GenAI Applications
                </h1>
                <p>
                    Text: GPT-3, LaMDA, LLaMA, BLOOM and GPT-4.
                    Code: OpenAI Codex.
                    Images: DALL-E, Midjourney and Stable Diffusion.
                    Video: Make-A-Video (Meta Platforms).
                    Wikipedia
                </p>
                <div class="read-more">
                    <a asp-area="" asp-controller="Home" asp-action="GenAiApplications">Read More</a>
                </div>
            </div>
            <div class="images">
                <div class="image-1">
                    <img src="@Url.Content("/images/genaisites/chatgpt_thumbnail.jpg")"
                         alt="" />
                </div>
                <div class="image-2">
                    <img src="@Url.Content("/images/genaisites/dalle_thumbnail.jpg")"
                         alt="" />
                </div>
            </div>
        </div>

        <div class="blog-card">
            <div class="images">
                <div class="image-1">
                    <img src="@Url.Content("/images/genaisites/pie.jpg")"
                         alt="" />
                </div>
                <div class="image-2">
                    <img src="@Url.Content("/images/genaisites/job.jpg")"
                         alt="" />
                </div>
            </div>
            <div class="description">
                <h1>
                    AI Jobs
                </h1>
                <p>
                    The prime source for jobs and talents in AI, ML, Data Science and Big Data: Insights AIJobs
                    Python source for tables and charts: Kaggle.

                </p>
                <div class="read-more">
                    <a asp-area="" asp-controller="Jobs" asp-action="Index">Read More</a>
                </div>
            </div>

        </div>
        <div class="parallax-container-list">
            <h1 class="custom-h1">GenAI List</h1>
            <a class="parallax-container-list-a" asp-controller="GenAIs" asp-action="Create">Click Here to add new genrate AI website</a>
        <div class="row">
            @foreach (var item in Model)
            {
                <div class="col-6 col-md-4 col-lg-2 mb-4">
                    <a href="@Url.Action("Index", "GenAIs")">
                        <div class="custom-tile">
                            <p class="tile-title">@item.GenAIName</p>
                            <img src="~/images/@item.ImageFilename" class="tile-image" alt="GenAI Image">
                        </div>
                    </a>
                </div>
            }
        </div>
        </div>

    </div>
}
else
{
    <div class="hero-section">
        <video loop muted autoplay="autoplay" preload="auto" id="background-video">
            <source src="@Url.Content("~/videos/video.mp4")" type="video/mp4">
        </video>
        <div class="overlay"></div>
        <div class="video-content">
            <h1 class="main-heading">Generative AI Technology</h1>
            <div class="content">
                <p>
                    Any time an AI technology is generating something on its own, it can be referred to as
                    "generative AI." This umbrella term includes learning algorithms that make predictions
                    as well as those that can use prompts to autonomously write articles and paint pictures.
                    Techopedia
                </p>
            </div>
        </div>
    </div>
   
        
  
    <div class="parallax-container ">
        <div class="blog-card">
            <div class="description">
                <h1>
                    GenAI Tools
                </h1>
                <p>
                    Generative AI tools refer to software or systems that use neural network techniques to
                    process and comprehend input data, subsequently producing meaningful responses.
                    Scribehow
                </p>
                <div class="read-more">
                    <a href="#">Read More</a>
                </div>
            </div>
            <div class="images">
                <div class="image-1">
                    <img src="@Url.Content("/images/genaisites/bard_thumbnail.jpg")"
                         alt="" />
                </div>
                <div class="image-2">
                    <img src="@Url.Content("/images/genaisites/midjourney_thumbnail.jpg")"
                         alt="" />
                </div>
            </div>
        </div>
            <div class="blog-card">
                <div class="images">
                    <div class="image-1">
                        <img src="@Url.Content("/images/genaisites/ms_thumbnail.jpg")"
                             alt="" />
                    </div>
                    <div class="image-2">
                        <img src="@Url.Content("/images/genaisites/google_thumbnail.jpg")"
                             alt="" />
                    </div>
                </div>
                <div class="description">
                    <h1>
                        GenAI Organisations
                    </h1>
                    <p>
                        Generative AI Organizations like Microsoft, Google, Amazon and IBM have invested
                        hundreds of millions of dollars and massive compute power to build the foundational
                        models on which services like ChatGPT and others depend.
                        Gartner
                    </p>
                    <div class="read-more">
                        <a href="#">Read More</a>
                    </div>
                </div>

            </div>

        <div class="blog-card">
            <div class="description">
                <h1>
                    GenAI Applications
                </h1>
                <p>
                    Text: GPT-3, LaMDA, LLaMA, BLOOM and GPT-4.
                    Code: OpenAI Codex.
                    Images: DALL-E, Midjourney and Stable Diffusion.
                    Video: Make-A-Video (Meta Platforms).
                    Wikipedia
                </p>
                <div class="read-more">
                    <a href="#">Read More</a>
                </div>
            </div>
            <div class="images">
                <div class="image-1">
                    <img src="@Url.Content("/images/genaisites/chatgpt_thumbnail.jpg")"
                         alt="" />
                </div>
                <div class="image-2">
                    <img src="@Url.Content("/images/genaisites/dalle_thumbnail.jpg")"
                         alt="" />
                </div>
            </div>
        </div>

        <div class="blog-card">
            <div class="images">
                <div class="image-1">
                    <img src="@Url.Content("/images/genaisites/pie.jpg")"
                         alt="" />
                </div>
                <div class="image-2">
                    <img src="@Url.Content("/images/genaisites/job.jpg")"
                         alt="" />
                </div>
            </div>
            <div class="description">
                <h1>
                    AI Jobs
                </h1>
                <p>
                    The prime source for jobs and talents in AI, ML, Data Science and Big Data: Insights AIJobs
                    Python source for tables and charts: Kaggle.

                </p>
                <div class="read-more">
                    <a href="#">Read More</a>
                </div>
            </div>

        </div>
        <div class="parallax-container-list">
            <h1 class="custom-h1">GenAI List</h1>
            <a class="parallax-container-list-a" >Please login or register to add a new generative AI website.</a>
            <div class="row">
                @foreach (var item in Model)
                {
                    <div class="col-6 col-md-4 col-lg-2 mb-4">
                        <a href="@Url.Action("Index", "GenAIs")">
                            <div class="custom-tile">
                                <p class="tile-title">@item.GenAIName</p>
                                <img src="~/images/@item.ImageFilename" class="tile-image" alt="GenAI Image">
                            </div>
                        </a>
                    </div>
                }
            </div>
        </div>
        
    </div>
}








<script>
    document.querySelectorAll('.fade-in').forEach(element => {
        element.addEventListener('mouseover', () => {
            element.style.opacity = '1';
        });
        element.addEventListener('click', () => {
            window.location.href = "GenAIs";
        });
    });

    document.querySelectorAll('.custom-tile').forEach(element => {
        element.addEventListener('click', () => {
            console.log("Test");
        });
    });
 
</script>